#! /bin/sh

n=$1
if (test -z "$n") then
    exit -1
fi
if (test $n -lt 3) then
    exit -1
fi

p=$2
if (test -z "$p") then
    exit -1
fi

q=$3
if (test -z "$q") then
    exit -1
fi

np=`perl -e "print 1-$p"`
nq=`perl -e "print 1-$q"`

echo "stochastic"
echo
echo "const n = $n;"
echo "rate p = $p;"
echo "rate np = $np;"
echo "rate q = $q;"
echo "rate nq = $nq;"
echo
echo "module M"
echo
echo "  s : [1..n];"
echo
echo "  [] (s<n-2) -> q : (s'=s+1);"
echo "  [] (s<n-2) -> nq : (s'=1);"
echo "  [] (s=n-2) -> p : (s'=n);"
echo "  [] (s=n-2) -> np : (s'=n-1);"
echo
echo "endmodule"
