#! /usr/local/bin/bash

ulimit -v `expr 700 '*' 1024`
echo memory limit: `ulimit -v` kbytes

if (test ! -e data) then
    mkdir data
fi

trials=10

function sampling-test {
    dst=data/tandem$n-$T-sampling-$i-$d
    echo $dst
    if (test ! -e $dst) then
	scripts/tandem-property $T | ./ymer -v1  -e sampling -T $trials -S 0 -A 1e-$i -B 1e-$i -D 0.$d models/tandem$n.sm /dev/stdin > $dst
    fi
}

function hybrid-test {
    if (test $n -lt 4095) then
	dst=data/tandem$n-$T-hybrid
	echo $dst
	if (test ! -e $dst) then
	    scripts/tandem-property $T | ./ymer -v1 -e hybrid -E 1e-6 models/tandem$n.sm /dev/stdin > $dst
	fi
    fi
}

i=2
d=005
for T in 5 50 500; do
    for n in 1 3 7 15 31 63 127 255 511 1023 2047 4095 8191 16383 32767 65535; do
	sampling-test
    done
    for n in 1 3 7 15 31 63 127 255 511 1023 2047; do
	hybrid-test
    done
done
T=50
for n in 2 4 5; do
    sampling-test
done
for n in 16; do
    hybrid-test
done
T=500
for n in 2 4 5 6 10; do
    sampling-test
done
for n in 16; do
    hybrid-test
done

for n in 3 31 255; do
    for T in 2 5 10 25 50 100 250 500 1000 2500 5000 10000; do
	sampling-test
	hybrid-test
    done
done
n=3
for T in 65 68 75 77 78 79 80 82 87 145; do
    sampling-test
done
n=3
for T in 1116; do
    hybrid-test
done
n=31
for T in 16; do
    hybrid-test
done
n=255
for T in 14; do
    hybrid-test
done
