#! /bin/sh

if (test ! -e plots/data) then
    mkdir plots/data
fi

stkey='Average model checking time: '
tdkey='Time standard deviation: '
skey='Average number of samples: '
sdkey='Samples standard deviation: '
akey=' accepted, '
pkey='Average path lengths: '
htkey='Model checking completed in '
ikey='Computing probabilities'

function sampling-data {
    src=data/tandem$n-$T-sampling-$i-$d
    if (test -f $src) then
	t=`grep "$stkey" $src | sed -e "s/$stkey//g" -e 's/ seconds//g'`
	if (test "$t" = "0") then
	    t=1e-3
	fi
	td=`grep "$tdkey" $src | sed -e "s/$tdkey//g"`
	s=`grep "$skey" $src | sed -e "s/$skey//g"`
	sd=`grep "$sdkey" $src | sed -e "s/$sdkey//g"`
	p=`grep "$pkey" $src | sed -e "s/$pkey//g"`
	a=`grep "$akey" $src | sed -e "s/$akey.*//g"`
	if (test "$t") then
	    echo $1 $t $td $s $sd $p $a >> $sdst
	fi
    fi
}

function hybrid-data {
    src=data/tandem$n-$T-hybrid
    if (test -f $src) then
	t=`grep "$htkey" $src | sed -e "s/$htkey//g" -e 's/ seconds.//g'`
	if (test "$t" = "0") then
	    t=1e-3
	fi
	j=`grep "$ikey" $src | sed -e "s/$ikey[.:]*//g" -e 's/ iterations.//g'`
	s=`grep 'Steady state' $src`
	if (test "$s") then
	    s=1
	else
	    s=0
	fi
	a=`grep 'Property is true' $src`
	if (test "$a") then
	    a=1
	else
	    a=0
	fi
	if (test "$t") then
	    echo $1 $t $j $s $a >> $hdst
	fi
    fi
}

i=2
d=005
for T in 5 50 500; do
    echo tandemN-$T
    sdst=plots/data/tandemN-$T-sampling-$i-$d
    hdst=plots/data/tandemN-$T-hybrid
    touch $sdst
    touch $hdst
    for n in 1 2 3 4 5 6 7 10 15 16 31 63 127 255 511 1023 2047 4095 8191 16383 32767 65535; do
	echo $n
        sampling-data $n
        hybrid-data $n
    done
done
for n in 3 31 255; do
    echo tandem$n-T
    sdst=plots/data/tandem$n-T-sampling-$i-$d
    hdst=plots/data/tandem$n-T-hybrid
    touch $sdst
    touch $hdst
    for T in 2 5 10 14 16 25 50 65 68 75 77 78 79 80 82 87 100 145 250 500 1000 1116 2500 5000 10000; do
	echo $T
	sampling-data $T
	hybrid-data $T
    done
done
