#! /bin/sh

if (test ! -d models) then
    mkdir models
fi

for n in 2 4 6 8 9 10 11 12 13 14 16 18 19 20 21 22 24 26 28 30 32 34 36 38 39 40; do
    echo $n
    if (test ! -f models/polling$n.sm) then
	scripts/polling-model $n > models/polling$n.sm
    fi
done
