#! /bin/sh

if (test ! -e plots/data) then
    mkdir -p plots/data
fi

stkey='Average model checking time: '
tdkey='Time standard deviation: '
skey='Average number of samples: '
sdkey='Samples standard deviation: '
akey=' accepted, '
pkey='Average path lengths: '
htkey='Model checking completed in '
ikey='Computing probabilities'

function sampling-data {
    src=data/cluster$n-$T-sampling-$i-$d
    if (test -f $src) then
	t=`grep "$stkey" $src | sed -e "s/$stkey//g" -e 's/ seconds//g'`
	if (test "$t" = "0") then
	    t=1e-3
	fi
	td=`grep "$tdkey" $src | sed -e "s/$tdkey//g"`
	s=`grep "$skey" $src | sed -e "s/$skey//g"`
	sd=`grep "$sdkey" $src | sed -e "s/$sdkey//g"`
	p=`grep "$pkey" $src | sed -e "s/$pkey//g"`
	a=`grep "$akey" $src | sed -e "s/$akey.*//g"`
	if (test "$t") then
	    echo $1 $t $td $s $sd $p $a >> $sdst
	fi
    fi
}

function hybrid-data {
    src=data/cluster$n-$T-hybrid
    if (test -f $src) then
	t=`grep "$htkey" $src | sed -e "s/$htkey//g" -e 's/ seconds.//g'`
	if (test "$t" = "0") then
	    t=1e-3
	fi
	j=`grep "$ikey" $src | sed -e "s/$ikey[.:]*//g" -e 's/ iterations.//g'`
	s=`grep 'Steady state' $src`
	if (test "$s") then
	    s=1
	else
	    s=0
	fi
	a=`grep 'Property is true' $src`
	if (test "$a") then
	    a=1
	else
	    a=0
	fi
	if (test "$t") then
	    echo $1 $t $j $s $a >> $hdst
	fi
    fi
}

i=2
d=005
for T in 20 40 80; do
    echo clusterN-$T
    sdst=plots/data/clusterN-$T-sampling-$i-$d
    hdst=plots/data/clusterN-$T-hybrid
    for n in 1 2 3 4 8 16 32 64 128 256 512 856 1024 2048 4096 8192 16384 32768 65536; do
	echo $n
	sampling-data $n
	hybrid-data $n
    done
done
for n in 4 16 64; do
    echo cluster$n-T
    sdst=plots/data/cluster$n-T-sampling-$i-$d
    hdst=plots/data/cluster$n-T-hybrid
    for T in 2 5 10 25 50 100 250 500 1000 2500 5000 10000; do
	echo $T
	sampling-data $T
	hybrid-data $T
    done
done

n=64
T=80
for i in 2 4 6 8 10; do
    echo cluster-$i-D
    sdst=plots/data/cluster$n-$T-sampling-$i-D
    for d in 05 025 01 005 0025 001 0005 00025 0001 00005; do
	echo $d
	sampling-data 0.$d
    done
done
