#! /bin/sh

if (test ! -d models) then
    mkdir models
fi

for n in 2 4 7 8 9 10 12 16 32 64 128 180 181 256 512 1024 2048 4096 8192; do
    echo $n
    if (test ! -f models/robot$n.sm) then
	scripts/robot-model $n > models/robot$n.sm
    fi
done
