#! /bin/sh
#
# Runs Ymer as a server on the local machine, with two sample
# generating clients on machines named `sweden' and `gs222'.
#
# Run as `scripts/ymer-dist2 <model file> <property file>

params='-v1 -S1 -D0.005'
./ymer $params -p 5000 $1 $2 &

ssh sweden "cd ~/ymer-2.1; ./ymer $params -h `hostname` -p 5000 $1 $2" &
ssh gs222 "cd /usr1/research/ymer-2.1; ./ymer $params -h `hostname` -p 5000 $1 $2" &
