#! /bin/sh

if (test ! -d models) then
    mkdir models
fi

for n in 1 2 3 4 5 6 7 10 15 31 63 127 255 511 1023 2047 4095 8191 16383 32767 65535; do
    echo $n
    if (test ! -f models/tandem$n.sm) then
	scripts/tandem-model $n > models/tandem$n.sm
    fi
done
