#! /bin/bash

ulimit -v `expr 700 '*' 1024`
echo memory limit: `ulimit -v` kbytes

if (test ! -e data) then
    mkdir data
fi

trials=20

function sequential-test {
    dst=data/polling$n-$T-sequential-$i-$d
    echo $dst
    if (test ! -e $dst) then
	scripts/polling-property $T | ./ymer -v1  -e sampling -s sequential -T $trials -S 0 -A 1e-$i -B 1e-$i -D 0.$d models/polling$n.sm /dev/stdin > $dst
    fi
}

function sprt-test {
    dst=data/polling$n-$T-sprt-$i-$d
    echo $dst
    if (test ! -e $dst) then
	scripts/polling-property $T | ./ymer -v1  -e sampling -s sprt -T $trials -S 0 -A 1e-$i -B 1e-$i -D 0.$d models/polling$n.sm /dev/stdin > $dst
    fi
}

function hybrid-test {
    if (test $n -lt 20) then
	dst=data/polling$n-$T-hybrid
	echo $dst
	if (test ! -e $dst) then
	    scripts/polling-property $T | ./ymer -v1 -e hybrid -E 1e-6 models/polling$n.sm /dev/stdin > $dst
	fi
    fi
}

d=005
T=20
for i in 1 2 4 8; do
    for n in 2 4 6 8 10 12 14 16 18 19 20 21 22 24 26 28 30 32 34 36 38 40; do
	sequential-test
	sprt-test
    done
done

n=10
for i in 1 2 4 8; do
    for T in 2 5 7 8 9 10 11 12 15 25 50 100 250 500 1000; do
	sequential-test
	sprt-test
    done
done

#n=10
#T=40
#for i in 2 4 6 8 10; do
#    for d in 05 025 01 005 0025 001 0005 00025 0001 00005; do
#	sampling-test
#    done
#done
